movie/app/urls.py
from django.contrib import admin
from django.urls import path
from  app import views
app_name="app"
urlpatterns = [
    path('',views.home,name="home"),
    #path('', views.HomeView.as_view(), name="home"),
    path('detail/<int:n>/',views.detail,name="detail"),
    path('addmovie',views.addmovie,name="addmovie"),
    path('update/<int:n>/',views.update,name="update"),
    path('delete/<int:n>/',views.delete,name="delete"),


]

movie/movie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/app/models.py
from django.db import models

class Movie(models.Model):  #Movie table definition
    name=models.CharField(max_length=30)
    desc=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='movies',null=True,blank=True)

    def __str__(self):
        return self.name

movie/app/forms.py
from django import forms
from app.models import Movie

class movieform(forms.ModelForm): #Form definition
    class Meta:
        model=Movie
        fields="__all__"

movie/app/views.py
from django.shortcuts import render
from app.models import Movie
from app.forms import movieform
def home(request):
   m=Movie.objects.all()
   return render(request, 'home.html', {'m': m})


def detail(request,n):
   m = Movie.objects.get(id=n)
   return render(request, 'detail.html', {'m': m})
def addmovie(request):
    if(request.method=="POST"):
         form=movieform(request.POST,request.FILES)
         if form.is_valid():
            form.save()
            return home(request)

    form=movieform()
    return render(request, 'add.html', {'form': form})
def update(request,n):
    m = Movie.objects.get(id=n)
    if (request.method == "POST"):
        form = movieform(request.POST, request.FILES,instance=m)
        if form.is_valid():
            form.save()
            return home(request)

    form = movieform(instance=m)
    return render(request, 'add.html', {'form': form})
def delete(request,n):
    m = Movie.objects.get(id=n)
    m.delete()
    return home(request)

movie/templates/add.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
<center>
<h2 class="text-center">ADD MEDIA</h2>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<table>
    {{form.as_table}}
</table>
    <input type="submit">

</form>
</center>
</div>
{% endblock %}

movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
<nav class="navbar navbar-light" style="background-color:#e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand">Online Movie Store</a>
    <form class="d-flex">

      <a href="{% url 'app:addmovie' %}" class="btn btn-secondary text-dark">Add Movie</a>
    </form>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</htmt>

movie/templates/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row mt-5" style="margin-left:100px;">
        <div class="col-sm-6"><img src="{{m.image.url}}" height="300px" width="300px"></div>
        <div class="col-sm-6" style="text-align:justify;">
            <h3>{{m.name}}</h3>

            <p>{{m.desc}}</p>
            <a href="{% url 'app:update' m.id %}" class="btn btn-secondary text-dark">Update</a>
            <a  href="{% url 'app:delete' m.id %}" class="btn btn-secondary text-dark">Delete</a>

        </div>
    </div>

</div>
{% endblock %}

movie/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        {% for i in m %}
        <div class="col-sm-4 mt-4 mb-4">
<div class="card" style="width:19rem;">
  <img src="{{i.image.url}}" height="300px" width="300px" class="card-img-top" alt="...">
  <div class="card-body" style="background-color:#e3f2fd">
    <h5 class="card-title">{{i.name}}</h5>
         <p class="card-text">{{i.year}}</p>





    <a href="{% url 'app:detail' i.id %}" class="btn btn-primary">Details...</a>
  </div>
</div>




        </div>

        {% endfor %}



    </div>
</div>

{% endblock %}